### ISSUE TITLE
[idea] get obsidian style + link to open searchbar

### ISSUE THREAD

**Issue by daxcore** [ObsidianPublisher/mkdocs-custom-tags-attributes#5]
with the following javascript, a tag will change into a link (obsidian style), which opens the searchbar for material theme of mkdocs.

prerequisites: jQuery from official homepage.

```
plugins:
  - search
  - custom-attributes:
      file: assets/css/custom_attributes.css

extra_css:
    - assets/css/custom_attributes.css

extra_javascript:
    - assets/javascript/jquery-3.7.1.min.js
    - assets/javascript/custom_attributes.js
```
the javascript file:
```
$('.hash').each(function() {
  var link = $(this).html();
  $(this).contents().wrap('<a href="?q='+link+'">#</a>');
});
```

my css file:
```
.hash {
  background-color: #f3eefd;
  border-radius: 20px;
  padding: 5px;
  font-weight: normal;
}
```
